// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class RadialBarGroup
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject radialBarGroupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.RadialBarGroup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GroupId("GroupId"),
		RadialBarGroup_RadialBarContainer("MyFirstModule.RadialBarGroup_RadialBarContainer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RadialBarGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RadialBarGroup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject radialBarGroupMendixObject)
	{
		if (radialBarGroupMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, radialBarGroupMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.radialBarGroupMendixObject = radialBarGroupMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RadialBarGroup.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.RadialBarGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.RadialBarGroup.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.RadialBarGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.RadialBarGroup(context, mendixObject);
	}

	public static myfirstmodule.proxies.RadialBarGroup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.RadialBarGroup.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.RadialBarGroup> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.RadialBarGroup.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GroupId
	 */
	public final java.lang.String getGroupId()
	{
		return getGroupId(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupId
	 */
	public final java.lang.String getGroupId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GroupId.toString());
	}

	/**
	 * Set value of GroupId
	 * @param groupid
	 */
	public final void setGroupId(java.lang.String groupid)
	{
		setGroupId(getContext(), groupid);
	}

	/**
	 * Set value of GroupId
	 * @param context
	 * @param groupid
	 */
	public final void setGroupId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String groupid)
	{
		getMendixObject().setValue(context, MemberNames.GroupId.toString(), groupid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RadialBarGroup_RadialBarContainer
	 */
	public final myfirstmodule.proxies.RadialBarContainer getRadialBarGroup_RadialBarContainer() throws com.mendix.core.CoreException
	{
		return getRadialBarGroup_RadialBarContainer(getContext());
	}

	/**
	 * @param context
	 * @return value of RadialBarGroup_RadialBarContainer
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RadialBarContainer getRadialBarGroup_RadialBarContainer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RadialBarContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RadialBarGroup_RadialBarContainer.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RadialBarContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RadialBarGroup_RadialBarContainer
	 * @param radialbargroup_radialbarcontainer
	 */
	public final void setRadialBarGroup_RadialBarContainer(myfirstmodule.proxies.RadialBarContainer radialbargroup_radialbarcontainer)
	{
		setRadialBarGroup_RadialBarContainer(getContext(), radialbargroup_radialbarcontainer);
	}

	/**
	 * Set value of RadialBarGroup_RadialBarContainer
	 * @param context
	 * @param radialbargroup_radialbarcontainer
	 */
	public final void setRadialBarGroup_RadialBarContainer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RadialBarContainer radialbargroup_radialbarcontainer)
	{
		if (radialbargroup_radialbarcontainer == null) {
			getMendixObject().setValue(context, MemberNames.RadialBarGroup_RadialBarContainer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RadialBarGroup_RadialBarContainer.toString(), radialbargroup_radialbarcontainer.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return radialBarGroupMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.RadialBarGroup that = (myfirstmodule.proxies.RadialBarGroup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
