// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nivotestdata.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the NivoTestData module
	public static boolean aCoADe_LondonOlympicMedalCount(IContext context, nivotestdata.proxies.LondonOlympicMedalCount _londonOlympicMedalCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LondonOlympicMedalCount", _londonOlympicMedalCount == null ? null : _londonOlympicMedalCount.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("NivoTestData.ACoADe_LondonOlympicMedalCount").withParams(params).execute(context);
	}
	public static void aCT_CustomConfigurationUpdated_Margin(IContext context, nivotestdata.proxies.CustomConfiguration _customConfiguration, nivotestdata.proxies.ChartPlayground _chartPlayground)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CustomConfiguration", _customConfiguration == null ? null : _customConfiguration.getMendixObject());
		params.put("ChartPlayground", _chartPlayground == null ? null : _chartPlayground.getMendixObject());
		Core.microflowCall("NivoTestData.ACT_CustomConfigurationUpdated_Margin").withParams(params).execute(context);
	}
	public static void aCT_OpenChartPlayground(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("NivoTestData.ACT_OpenChartPlayground").withParams(params).execute(context);
	}
	public static void aCT_SaveLondonOlympicMedalCount(IContext context, nivotestdata.proxies.LondonOlympicMedalCount _londonOlympicMedalCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LondonOlympicMedalCount", _londonOlympicMedalCount == null ? null : _londonOlympicMedalCount.getMendixObject());
		Core.microflowCall("NivoTestData.ACT_SaveLondonOlympicMedalCount").withParams(params).execute(context);
	}
	public static nivotestdata.proxies.ChartPlayground dS_GetOrCreateChartPlayground(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("NivoTestData.DS_GetOrCreateChartPlayground").withParams(params).execute(context);
		return result == null ? null : nivotestdata.proxies.ChartPlayground.initialize(context, result);
	}
	public static void sUB_LondonOlympicMedalCount_Refresh(IContext context, nivotestdata.proxies.ChartPlayground _chartPlayground)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ChartPlayground", _chartPlayground == null ? null : _chartPlayground.getMendixObject());
		Core.microflowCall("NivoTestData.SUB_LondonOlympicMedalCount_Refresh").withParams(params).execute(context);
	}
	public static void sUB_RefreshChartPlaygroundData(IContext context, nivotestdata.proxies.ChartPlayground _chartPlayground)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ChartPlayground", _chartPlayground == null ? null : _chartPlayground.getMendixObject());
		Core.microflowCall("NivoTestData.SUB_RefreshChartPlaygroundData").withParams(params).execute(context);
	}
	public static void sUB_RefreshLondonOlympicMedalCount(IContext context, nivotestdata.proxies.ChartPlayground _chartPlayground)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ChartPlayground", _chartPlayground == null ? null : _chartPlayground.getMendixObject());
		Core.microflowCall("NivoTestData.SUB_RefreshLondonOlympicMedalCount").withParams(params).execute(context);
	}
}
