// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nivodatavisualisation.proxies;

public class ChartConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chartConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NivoDataVisualisation.ChartConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Padding("Padding"),
		CornerRadius("CornerRadius"),
		StartAngle("StartAngle"),
		EndAngle("EndAngle"),
		InnerRadius("InnerRadius"),
		PadAngle("PadAngle"),
		BorderWidth("BorderWidth"),
		ChartConfiguration_Margin("NivoDataVisualisation.ChartConfiguration_Margin"),
		ChartConfiguration_CircularAxisOuter("NivoDataVisualisation.ChartConfiguration_CircularAxisOuter"),
		ChartConfiguration_RadialAxisStart("NivoDataVisualisation.ChartConfiguration_RadialAxisStart");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChartConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ChartConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chartConfigurationMendixObject)
	{
		if (chartConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, chartConfigurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.chartConfigurationMendixObject = chartConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ChartConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nivodatavisualisation.proxies.ChartConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nivodatavisualisation.proxies.ChartConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nivodatavisualisation.proxies.ChartConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nivodatavisualisation.proxies.ChartConfiguration(context, mendixObject);
	}

	public static nivodatavisualisation.proxies.ChartConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nivodatavisualisation.proxies.ChartConfiguration.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Padding
	 */
	public final java.math.BigDecimal getPadding()
	{
		return getPadding(getContext());
	}

	/**
	 * @param context
	 * @return value of Padding
	 */
	public final java.math.BigDecimal getPadding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Padding.toString());
	}

	/**
	 * Set value of Padding
	 * @param padding
	 */
	public final void setPadding(java.math.BigDecimal padding)
	{
		setPadding(getContext(), padding);
	}

	/**
	 * Set value of Padding
	 * @param context
	 * @param padding
	 */
	public final void setPadding(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal padding)
	{
		getMendixObject().setValue(context, MemberNames.Padding.toString(), padding);
	}

	/**
	 * @return value of CornerRadius
	 */
	public final java.lang.Integer getCornerRadius()
	{
		return getCornerRadius(getContext());
	}

	/**
	 * @param context
	 * @return value of CornerRadius
	 */
	public final java.lang.Integer getCornerRadius(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CornerRadius.toString());
	}

	/**
	 * Set value of CornerRadius
	 * @param cornerradius
	 */
	public final void setCornerRadius(java.lang.Integer cornerradius)
	{
		setCornerRadius(getContext(), cornerradius);
	}

	/**
	 * Set value of CornerRadius
	 * @param context
	 * @param cornerradius
	 */
	public final void setCornerRadius(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cornerradius)
	{
		getMendixObject().setValue(context, MemberNames.CornerRadius.toString(), cornerradius);
	}

	/**
	 * @return value of StartAngle
	 */
	public final java.lang.Integer getStartAngle()
	{
		return getStartAngle(getContext());
	}

	/**
	 * @param context
	 * @return value of StartAngle
	 */
	public final java.lang.Integer getStartAngle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StartAngle.toString());
	}

	/**
	 * Set value of StartAngle
	 * @param startangle
	 */
	public final void setStartAngle(java.lang.Integer startangle)
	{
		setStartAngle(getContext(), startangle);
	}

	/**
	 * Set value of StartAngle
	 * @param context
	 * @param startangle
	 */
	public final void setStartAngle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer startangle)
	{
		getMendixObject().setValue(context, MemberNames.StartAngle.toString(), startangle);
	}

	/**
	 * @return value of EndAngle
	 */
	public final java.lang.String getEndAngle()
	{
		return getEndAngle(getContext());
	}

	/**
	 * @param context
	 * @return value of EndAngle
	 */
	public final java.lang.String getEndAngle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndAngle.toString());
	}

	/**
	 * Set value of EndAngle
	 * @param endangle
	 */
	public final void setEndAngle(java.lang.String endangle)
	{
		setEndAngle(getContext(), endangle);
	}

	/**
	 * Set value of EndAngle
	 * @param context
	 * @param endangle
	 */
	public final void setEndAngle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endangle)
	{
		getMendixObject().setValue(context, MemberNames.EndAngle.toString(), endangle);
	}

	/**
	 * @return value of InnerRadius
	 */
	public final java.math.BigDecimal getInnerRadius()
	{
		return getInnerRadius(getContext());
	}

	/**
	 * @param context
	 * @return value of InnerRadius
	 */
	public final java.math.BigDecimal getInnerRadius(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.InnerRadius.toString());
	}

	/**
	 * Set value of InnerRadius
	 * @param innerradius
	 */
	public final void setInnerRadius(java.math.BigDecimal innerradius)
	{
		setInnerRadius(getContext(), innerradius);
	}

	/**
	 * Set value of InnerRadius
	 * @param context
	 * @param innerradius
	 */
	public final void setInnerRadius(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal innerradius)
	{
		getMendixObject().setValue(context, MemberNames.InnerRadius.toString(), innerradius);
	}

	/**
	 * @return value of PadAngle
	 */
	public final java.lang.Integer getPadAngle()
	{
		return getPadAngle(getContext());
	}

	/**
	 * @param context
	 * @return value of PadAngle
	 */
	public final java.lang.Integer getPadAngle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PadAngle.toString());
	}

	/**
	 * Set value of PadAngle
	 * @param padangle
	 */
	public final void setPadAngle(java.lang.Integer padangle)
	{
		setPadAngle(getContext(), padangle);
	}

	/**
	 * Set value of PadAngle
	 * @param context
	 * @param padangle
	 */
	public final void setPadAngle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer padangle)
	{
		getMendixObject().setValue(context, MemberNames.PadAngle.toString(), padangle);
	}

	/**
	 * @return value of BorderWidth
	 */
	public final java.lang.Integer getBorderWidth()
	{
		return getBorderWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of BorderWidth
	 */
	public final java.lang.Integer getBorderWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BorderWidth.toString());
	}

	/**
	 * Set value of BorderWidth
	 * @param borderwidth
	 */
	public final void setBorderWidth(java.lang.Integer borderwidth)
	{
		setBorderWidth(getContext(), borderwidth);
	}

	/**
	 * Set value of BorderWidth
	 * @param context
	 * @param borderwidth
	 */
	public final void setBorderWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer borderwidth)
	{
		getMendixObject().setValue(context, MemberNames.BorderWidth.toString(), borderwidth);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChartConfiguration_Margin
	 */
	public final nivodatavisualisation.proxies.Margin getChartConfiguration_Margin() throws com.mendix.core.CoreException
	{
		return getChartConfiguration_Margin(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartConfiguration_Margin
	 * @throws com.mendix.core.CoreException
	 */
	public final nivodatavisualisation.proxies.Margin getChartConfiguration_Margin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nivodatavisualisation.proxies.Margin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartConfiguration_Margin.toString());
		if (identifier != null) {
			result = nivodatavisualisation.proxies.Margin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChartConfiguration_Margin
	 * @param chartconfiguration_margin
	 */
	public final void setChartConfiguration_Margin(nivodatavisualisation.proxies.Margin chartconfiguration_margin)
	{
		setChartConfiguration_Margin(getContext(), chartconfiguration_margin);
	}

	/**
	 * Set value of ChartConfiguration_Margin
	 * @param context
	 * @param chartconfiguration_margin
	 */
	public final void setChartConfiguration_Margin(com.mendix.systemwideinterfaces.core.IContext context, nivodatavisualisation.proxies.Margin chartconfiguration_margin)
	{
		if (chartconfiguration_margin == null) {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_Margin.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_Margin.toString(), chartconfiguration_margin.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChartConfiguration_CircularAxisOuter
	 */
	public final nivodatavisualisation.proxies.CircularAxisOuter getChartConfiguration_CircularAxisOuter() throws com.mendix.core.CoreException
	{
		return getChartConfiguration_CircularAxisOuter(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartConfiguration_CircularAxisOuter
	 * @throws com.mendix.core.CoreException
	 */
	public final nivodatavisualisation.proxies.CircularAxisOuter getChartConfiguration_CircularAxisOuter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nivodatavisualisation.proxies.CircularAxisOuter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartConfiguration_CircularAxisOuter.toString());
		if (identifier != null) {
			result = nivodatavisualisation.proxies.CircularAxisOuter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChartConfiguration_CircularAxisOuter
	 * @param chartconfiguration_circularaxisouter
	 */
	public final void setChartConfiguration_CircularAxisOuter(nivodatavisualisation.proxies.CircularAxisOuter chartconfiguration_circularaxisouter)
	{
		setChartConfiguration_CircularAxisOuter(getContext(), chartconfiguration_circularaxisouter);
	}

	/**
	 * Set value of ChartConfiguration_CircularAxisOuter
	 * @param context
	 * @param chartconfiguration_circularaxisouter
	 */
	public final void setChartConfiguration_CircularAxisOuter(com.mendix.systemwideinterfaces.core.IContext context, nivodatavisualisation.proxies.CircularAxisOuter chartconfiguration_circularaxisouter)
	{
		if (chartconfiguration_circularaxisouter == null) {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_CircularAxisOuter.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_CircularAxisOuter.toString(), chartconfiguration_circularaxisouter.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChartConfiguration_RadialAxisStart
	 */
	public final nivodatavisualisation.proxies.RadialAxisStart getChartConfiguration_RadialAxisStart() throws com.mendix.core.CoreException
	{
		return getChartConfiguration_RadialAxisStart(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartConfiguration_RadialAxisStart
	 * @throws com.mendix.core.CoreException
	 */
	public final nivodatavisualisation.proxies.RadialAxisStart getChartConfiguration_RadialAxisStart(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nivodatavisualisation.proxies.RadialAxisStart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartConfiguration_RadialAxisStart.toString());
		if (identifier != null) {
			result = nivodatavisualisation.proxies.RadialAxisStart.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChartConfiguration_RadialAxisStart
	 * @param chartconfiguration_radialaxisstart
	 */
	public final void setChartConfiguration_RadialAxisStart(nivodatavisualisation.proxies.RadialAxisStart chartconfiguration_radialaxisstart)
	{
		setChartConfiguration_RadialAxisStart(getContext(), chartconfiguration_radialaxisstart);
	}

	/**
	 * Set value of ChartConfiguration_RadialAxisStart
	 * @param context
	 * @param chartconfiguration_radialaxisstart
	 */
	public final void setChartConfiguration_RadialAxisStart(com.mendix.systemwideinterfaces.core.IContext context, nivodatavisualisation.proxies.RadialAxisStart chartconfiguration_radialaxisstart)
	{
		if (chartconfiguration_radialaxisstart == null) {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_RadialAxisStart.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_RadialAxisStart.toString(), chartconfiguration_radialaxisstart.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chartConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nivodatavisualisation.proxies.ChartConfiguration that = (nivodatavisualisation.proxies.ChartConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
