// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nivodatavisualisation.proxies;

public class RadialAxisStart extends nivodatavisualisation.proxies.AxisBase
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NivoDataVisualisation.RadialAxisStart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TickSize("TickSize"),
		TickPadding("TickPadding"),
		TickRotation("TickRotation"),
		ChartConfiguration_RadialAxisStart("NivoDataVisualisation.ChartConfiguration_RadialAxisStart");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RadialAxisStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RadialAxisStart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject radialAxisStartMendixObject)
	{
		super(context, radialAxisStartMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, radialAxisStartMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'RadialAxisStart.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nivodatavisualisation.proxies.RadialAxisStart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nivodatavisualisation.proxies.RadialAxisStart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nivodatavisualisation.proxies.RadialAxisStart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nivodatavisualisation.proxies.RadialAxisStart(context, mendixObject);
	}

	public static nivodatavisualisation.proxies.RadialAxisStart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nivodatavisualisation.proxies.RadialAxisStart.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChartConfiguration_RadialAxisStart
	 */
	public final nivodatavisualisation.proxies.ChartConfiguration getChartConfiguration_RadialAxisStart() throws com.mendix.core.CoreException
	{
		return getChartConfiguration_RadialAxisStart(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartConfiguration_RadialAxisStart
	 * @throws com.mendix.core.CoreException
	 */
	public final nivodatavisualisation.proxies.ChartConfiguration getChartConfiguration_RadialAxisStart(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nivodatavisualisation.proxies.ChartConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartConfiguration_RadialAxisStart.toString());
		if (identifier != null) {
			result = nivodatavisualisation.proxies.ChartConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChartConfiguration_RadialAxisStart
	 * @param chartconfiguration_radialaxisstart
	 */
	public final void setChartConfiguration_RadialAxisStart(nivodatavisualisation.proxies.ChartConfiguration chartconfiguration_radialaxisstart)
	{
		setChartConfiguration_RadialAxisStart(getContext(), chartconfiguration_radialaxisstart);
	}

	/**
	 * Set value of ChartConfiguration_RadialAxisStart
	 * @param context
	 * @param chartconfiguration_radialaxisstart
	 */
	public final void setChartConfiguration_RadialAxisStart(com.mendix.systemwideinterfaces.core.IContext context, nivodatavisualisation.proxies.ChartConfiguration chartconfiguration_radialaxisstart)
	{
		if (chartconfiguration_radialaxisstart == null) {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_RadialAxisStart.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChartConfiguration_RadialAxisStart.toString(), chartconfiguration_radialaxisstart.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nivodatavisualisation.proxies.RadialAxisStart that = (nivodatavisualisation.proxies.RadialAxisStart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
