// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nivotestdata.proxies;

public class ChartPlayground
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chartPlaygroundMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NivoTestData.ChartPlayground";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Data("Data"),
		Configuration("Configuration"),
		ChartPlayground_CustomConfiguration("NivoTestData.ChartPlayground_CustomConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChartPlayground(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ChartPlayground(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chartPlaygroundMendixObject)
	{
		if (chartPlaygroundMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, chartPlaygroundMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.chartPlaygroundMendixObject = chartPlaygroundMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ChartPlayground.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nivotestdata.proxies.ChartPlayground initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nivotestdata.proxies.ChartPlayground.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nivotestdata.proxies.ChartPlayground initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nivotestdata.proxies.ChartPlayground(context, mendixObject);
	}

	public static nivotestdata.proxies.ChartPlayground load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nivotestdata.proxies.ChartPlayground.initialize(context, mendixObject);
	}

	public static java.util.List<nivotestdata.proxies.ChartPlayground> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nivotestdata.proxies.ChartPlayground.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Data
	 */
	public final java.lang.String getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.lang.String getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.lang.String data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of Configuration
	 */
	public final java.lang.String getConfiguration()
	{
		return getConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Configuration
	 */
	public final java.lang.String getConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Configuration.toString());
	}

	/**
	 * Set value of Configuration
	 * @param configuration
	 */
	public final void setConfiguration(java.lang.String configuration)
	{
		setConfiguration(getContext(), configuration);
	}

	/**
	 * Set value of Configuration
	 * @param context
	 * @param configuration
	 */
	public final void setConfiguration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String configuration)
	{
		getMendixObject().setValue(context, MemberNames.Configuration.toString(), configuration);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChartPlayground_CustomConfiguration
	 */
	public final nivotestdata.proxies.CustomConfiguration getChartPlayground_CustomConfiguration() throws com.mendix.core.CoreException
	{
		return getChartPlayground_CustomConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartPlayground_CustomConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final nivotestdata.proxies.CustomConfiguration getChartPlayground_CustomConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nivotestdata.proxies.CustomConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartPlayground_CustomConfiguration.toString());
		if (identifier != null) {
			result = nivotestdata.proxies.CustomConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChartPlayground_CustomConfiguration
	 * @param chartplayground_customconfiguration
	 */
	public final void setChartPlayground_CustomConfiguration(nivotestdata.proxies.CustomConfiguration chartplayground_customconfiguration)
	{
		setChartPlayground_CustomConfiguration(getContext(), chartplayground_customconfiguration);
	}

	/**
	 * Set value of ChartPlayground_CustomConfiguration
	 * @param context
	 * @param chartplayground_customconfiguration
	 */
	public final void setChartPlayground_CustomConfiguration(com.mendix.systemwideinterfaces.core.IContext context, nivotestdata.proxies.CustomConfiguration chartplayground_customconfiguration)
	{
		if (chartplayground_customconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ChartPlayground_CustomConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChartPlayground_CustomConfiguration.toString(), chartplayground_customconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chartPlaygroundMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nivotestdata.proxies.ChartPlayground that = (nivotestdata.proxies.ChartPlayground) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
