// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nivotestdata.proxies;

public class CustomConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NivoTestData.CustomConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApplyCustomMargin("ApplyCustomMargin"),
		MarginTop("MarginTop"),
		MarginRight("MarginRight"),
		MarginBottom("MarginBottom"),
		MarginLeft("MarginLeft"),
		ChartPlayground_CustomConfiguration("NivoTestData.ChartPlayground_CustomConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CustomConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CustomConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customConfigurationMendixObject)
	{
		if (customConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, customConfigurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.customConfigurationMendixObject = customConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CustomConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nivotestdata.proxies.CustomConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nivotestdata.proxies.CustomConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nivotestdata.proxies.CustomConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nivotestdata.proxies.CustomConfiguration(context, mendixObject);
	}

	public static nivotestdata.proxies.CustomConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nivotestdata.proxies.CustomConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<nivotestdata.proxies.CustomConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nivotestdata.proxies.CustomConfiguration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ApplyCustomMargin
	 */
	public final java.lang.Boolean getApplyCustomMargin()
	{
		return getApplyCustomMargin(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplyCustomMargin
	 */
	public final java.lang.Boolean getApplyCustomMargin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ApplyCustomMargin.toString());
	}

	/**
	 * Set value of ApplyCustomMargin
	 * @param applycustommargin
	 */
	public final void setApplyCustomMargin(java.lang.Boolean applycustommargin)
	{
		setApplyCustomMargin(getContext(), applycustommargin);
	}

	/**
	 * Set value of ApplyCustomMargin
	 * @param context
	 * @param applycustommargin
	 */
	public final void setApplyCustomMargin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean applycustommargin)
	{
		getMendixObject().setValue(context, MemberNames.ApplyCustomMargin.toString(), applycustommargin);
	}

	/**
	 * @return value of MarginTop
	 */
	public final java.lang.Integer getMarginTop()
	{
		return getMarginTop(getContext());
	}

	/**
	 * @param context
	 * @return value of MarginTop
	 */
	public final java.lang.Integer getMarginTop(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MarginTop.toString());
	}

	/**
	 * Set value of MarginTop
	 * @param margintop
	 */
	public final void setMarginTop(java.lang.Integer margintop)
	{
		setMarginTop(getContext(), margintop);
	}

	/**
	 * Set value of MarginTop
	 * @param context
	 * @param margintop
	 */
	public final void setMarginTop(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer margintop)
	{
		getMendixObject().setValue(context, MemberNames.MarginTop.toString(), margintop);
	}

	/**
	 * @return value of MarginRight
	 */
	public final java.lang.Integer getMarginRight()
	{
		return getMarginRight(getContext());
	}

	/**
	 * @param context
	 * @return value of MarginRight
	 */
	public final java.lang.Integer getMarginRight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MarginRight.toString());
	}

	/**
	 * Set value of MarginRight
	 * @param marginright
	 */
	public final void setMarginRight(java.lang.Integer marginright)
	{
		setMarginRight(getContext(), marginright);
	}

	/**
	 * Set value of MarginRight
	 * @param context
	 * @param marginright
	 */
	public final void setMarginRight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer marginright)
	{
		getMendixObject().setValue(context, MemberNames.MarginRight.toString(), marginright);
	}

	/**
	 * @return value of MarginBottom
	 */
	public final java.lang.Integer getMarginBottom()
	{
		return getMarginBottom(getContext());
	}

	/**
	 * @param context
	 * @return value of MarginBottom
	 */
	public final java.lang.Integer getMarginBottom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MarginBottom.toString());
	}

	/**
	 * Set value of MarginBottom
	 * @param marginbottom
	 */
	public final void setMarginBottom(java.lang.Integer marginbottom)
	{
		setMarginBottom(getContext(), marginbottom);
	}

	/**
	 * Set value of MarginBottom
	 * @param context
	 * @param marginbottom
	 */
	public final void setMarginBottom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer marginbottom)
	{
		getMendixObject().setValue(context, MemberNames.MarginBottom.toString(), marginbottom);
	}

	/**
	 * @return value of MarginLeft
	 */
	public final java.lang.Integer getMarginLeft()
	{
		return getMarginLeft(getContext());
	}

	/**
	 * @param context
	 * @return value of MarginLeft
	 */
	public final java.lang.Integer getMarginLeft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MarginLeft.toString());
	}

	/**
	 * Set value of MarginLeft
	 * @param marginleft
	 */
	public final void setMarginLeft(java.lang.Integer marginleft)
	{
		setMarginLeft(getContext(), marginleft);
	}

	/**
	 * Set value of MarginLeft
	 * @param context
	 * @param marginleft
	 */
	public final void setMarginLeft(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer marginleft)
	{
		getMendixObject().setValue(context, MemberNames.MarginLeft.toString(), marginleft);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChartPlayground_CustomConfiguration
	 */
	public final nivotestdata.proxies.ChartPlayground getChartPlayground_CustomConfiguration() throws com.mendix.core.CoreException
	{
		return getChartPlayground_CustomConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartPlayground_CustomConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final nivotestdata.proxies.ChartPlayground getChartPlayground_CustomConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nivotestdata.proxies.ChartPlayground result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChartPlayground_CustomConfiguration.toString());
		if (identifier != null) {
			result = nivotestdata.proxies.ChartPlayground.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChartPlayground_CustomConfiguration
	 * @param chartplayground_customconfiguration
	 */
	public final void setChartPlayground_CustomConfiguration(nivotestdata.proxies.ChartPlayground chartplayground_customconfiguration)
	{
		setChartPlayground_CustomConfiguration(getContext(), chartplayground_customconfiguration);
	}

	/**
	 * Set value of ChartPlayground_CustomConfiguration
	 * @param context
	 * @param chartplayground_customconfiguration
	 */
	public final void setChartPlayground_CustomConfiguration(com.mendix.systemwideinterfaces.core.IContext context, nivotestdata.proxies.ChartPlayground chartplayground_customconfiguration)
	{
		if (chartplayground_customconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ChartPlayground_CustomConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChartPlayground_CustomConfiguration.toString(), chartplayground_customconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nivotestdata.proxies.CustomConfiguration that = (nivotestdata.proxies.CustomConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
