// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.RadialBarContainer dS_RadialBarContainer(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_RadialBarContainer").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.RadialBarContainer.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.RadialBarGroup> dS_RadialBarGroupList(IContext context, myfirstmodule.proxies.RadialBarContainer _radialBarContainer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RadialBarContainer", _radialBarContainer == null ? null : _radialBarContainer.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_RadialBarGroupList").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.RadialBarGroup.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<myfirstmodule.proxies.RadialBarGroupMetric> dS_RadioBarGroupMetricList(IContext context, myfirstmodule.proxies.RadialBarContainer _radialBarContainer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RadialBarContainer", _radialBarContainer == null ? null : _radialBarContainer.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_RadioBarGroupMetricList").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> myfirstmodule.proxies.RadialBarGroupMetric.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
}
