// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package nivotestdata.actions;

import java.io.File;
import java.io.FileInputStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import org.apache.commons.io.IOUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Set the contents of a FileDocument with the contents of a file which is a resource.
 */
public class GetFileContentsFromResources extends CustomJavaAction<java.lang.String>
{
	private java.lang.String RelativeFilePath;

	public GetFileContentsFromResources(IContext context, java.lang.String RelativeFilePath)
	{
		super(context);
		this.RelativeFilePath = RelativeFilePath;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String path = Core.getConfiguration().getResourcesPath().getAbsolutePath();
		if(!path.endsWith(File.separator)) {
			path = path + File.separator;
		}		
		path = path + RelativeFilePath;
		File myFile = new File(path);

		Charset charset = StandardCharsets.UTF_8;
		try ( FileInputStream fis = new FileInputStream(myFile) ) {			
			return IOUtils.toString(fis, charset);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileContentsFromResources";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
