// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package nivotestdata.actions;

import java.nio.file.Paths;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetPath extends CustomJavaAction<java.lang.String>
{
	private java.lang.String FirstPart;
	private java.lang.String SecondPart;

	public GetPath(IContext context, java.lang.String FirstPart, java.lang.String SecondPart)
	{
		super(context);
		this.FirstPart = FirstPart;
		this.SecondPart = SecondPart;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Paths.get(FirstPart, SecondPart).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
